routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\{UserMasterController, RoleMasterController};

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

Route::get('/buyer','LeadDetailsController@lead_details');
Route::get('/','CompanyMasterController@index');
Route::get('addPcCompanyName','LeadDetailsController@addPcCompanyName');
Route::get('addPcExcecutiveName','LeadDetailsController@addPcExcecutiveName');
Route::get('addUnitInformation','LeadDetailsController@addUnitInformation');
Route::get('addUnitAmenity','LeadDetailsController@addUnitAmenity');
Route::get('addBuildingAmenity','LeadDetailsController@addBuildingAmenity');
Route::post('saveBuyer','LeadDetailsController@saveBuyer');

Route::post('lookingSince','LeadDetailsController@lookingSince');
Route::post('challenges_and_solutions','LeadDetailsController@challenges_and_solutions');
Route::get('/getMaximumBudget','LeadDetailsController@getMaximumBudget');
Route::get('/getOwnContribution','LeadDetailsController@getOwnContribution');
Route::get('/getUnitTypes','LeadDetailsController@getUnitTypes');
Route::post('getData1','LeadDetailsController@getData1');
Route::post('updateTableRecords','LeadDetailsController@updateTableRecords');
Route::post('deleteTableRecords','LeadDetailsController@deleteTableRecords');

Route::get('buyer-list-view','LeadDetailsController@buyerListView');
Route::get('getMinCarpetArea','LeadDetailsController@getMinCarpetArea');
Route::get('findlocationWithsublocationID','LeadDetailsController@findlocationWithsublocationID');
Route::get('getMaxCarpetArea','LeadDetailsController@getMaxCarpetArea');
Route::get('deleteBuyer','LeadDetailsController@deleteBuyer');
Route::get('deleteTenant','LeadDetailsController@deleteTenant');

// Buyer Filter
// Route::get('buyer-list-view','LeadDetailsController@buyerListView');


Route::get('addLocation','LeadDetailsController@addLocation');

Route::get('addResCity','LeadDetailsController@addResCity');
Route::get('addCompanyCity','LeadDetailsController@addCompanyCity');
Route::get('addDesignation','LeadDetailsController@addDesignation');
Route::get('addIndustry','LeadDetailsController@addIndustry');



Route::get('calculate_budget_break_up','LeadDetailsController@calculate_budget_break_up');
Route::get('download_budget_break_up','LeadDetailsController@download_budget_break_up');

Route::get('users-list','UserMasterController@index');
Route::get('user-form','UserMasterController@new_user');
Route::get('access-group','UserMasterController@access_group');

// User View
Route::get('user_master',[UserMasterController::class,'userView'])->name('user.userView');
Route::get('addUser',[UserMasterController::class,'addUser'])->name('user.addUser');
// Add user
Route::post('saveUser',[UserMasterController::class,'saveUser'])->name('user.saveUser');
// delete Image and resume
Route::post('delUserImage',[UserMasterController::class,'delUserImage']);
// status user
Route::post('statusUser',[UserMasterController::class,'statusUser']);
// delete user
Route::post('deleteUser',[UserMasterController::class,'deleteUser']);

// Change Password
Route::post('updatePasswordUser',[UserMasterController::class,'updatePasswordUser']);

// get Reporting Manger
Route::get('getUserReportingManagerData',[UserMasterController::class,'getUserReportingManagerData']);

Route::get('/register', 'UserMasterController@create');
Route::post('/register', 'UserMasterController@store');
         

// Roles View
Route::get('role_master',[RoleMasterController::class,'role_master'])->name('role.role_master');
// Add/Edit Access Level View
Route::get('add_role_access_level',[RoleMasterController::class,'add_role_access_level'])->name('role.add_role_access_level');
Route::post('saveRoleAccessGroup',[RoleMasterController::class,'saveRoleAccessGroup'])->name('role.saveRoleAccessGroup');

// Seller Controller
Route::get('seller','SellerController@index');
Route::get('addBuildingName','SellerController@addBuildingName');
Route::get('addWingName','SellerController@addWingName');
Route::get('addSuffixName','SellerController@addSuffixName');
Route::post('reasontoSell','SellerController@reason_to_sell');

// Owner Controller
Route::get('owner','OwnerController@index');

// Tenant Controller
Route::get('tenant','TenantController@index');
Route::get('getMaxRent','TenantController@getMaxRent');
Route::get('getMaxDeposit','TenantController@getMaxDeposit');
Route::post('savetenat','TenantController@saveTenat');
Route::get('tenant-list-view','TenantController@tenantListView');

Route::post('lookingSinceTenant','TenantController@lookingSinceTenant');
Route::post('challenges_and_solutions_tenant','TenantController@challenges_and_solutions_tenant');

// Company Master
Route::get('admin','CompanyMasterController@redirect');
Route::get('company-master','CompanyMasterController@index');
Route::any('add-company-master-form','CompanyMasterController@add_company_master_form');
Route::get('edit-company-master','CompanyMasterController@edit_company_master');
Route::get('addDesignationCompanyMaster','CompanyMasterController@addDesignationCompanyMaster');
Route::post('update-company-master','CompanyMasterController@update_company_master_form');
Route::get('searchData','CompanyMasterController@searchData');
Route::post('updateTableFormRecords','CompanyMasterController@updateTableFormRecords');
Route::post('deleteTableFormRecords','CompanyMasterController@deleteTableFormRecords');
Route::post('getData','CompanyMasterController@getData');
Route::get('company-list','CompanyMasterController@company_list');
Route::get('search-Company-List','CompanyMasterController@search_company_list');
Route::get('flow_chart_company','CompanyMasterController@flow_chart_company');
Route::post('delImage','CompanyMasterController@delImage');
Route::post('delImageHei','CompanyMasterController@delImageHei');
Route::post('delImageAward','CompanyMasterController@delImageAward');


Route::post('add-company-master','CompanyMasterController@add_company_master')->name('add-company-master');
Route::get('append_company_hierarchy_form','CompanyMasterController@append_company_hierarchy_form');

Route::get('logout','CompanyMasterController@logout');


// project Master
Route::get('project-master','ProjectMasterController@index');
Route::post('add-project-master','ProjectMasterController@add_project_master')->name('add-project-master');
Route::post('update-project-master','ProjectMasterController@update_project_master')->name('update-project-master');
Route::post('getDataProjet','ProjectMasterController@getDataProjet');
Route::post('updateProjectFormRecords','ProjectMasterController@updateProjectFormRecords');
Route::post('deleteProjectFormRecords','ProjectMasterController@deleteProjectFormRecords');
Route::get('findCityWithStateID','ProjectMasterController@findCityWithStateID');
Route::get('findlocationWithcityID','ProjectMasterController@findlocationWithcityID');
Route::get('findsublocationWithlocationID','ProjectMasterController@findsublocationWithlocationID');
Route::get('project-list','ProjectMasterController@project_list');
Route::get('search-project-List','ProjectMasterController@search_project_list');
Route::post('updateProjectAmenity','ProjectMasterController@updateProjectAmenity');
Route::post('addProjectAmenity','ProjectMasterController@addProjectAmenity');
Route::get('flow_chart_project','ProjectMasterController@flow_chart_project');
Route::post('createEmptyProject','ProjectMasterController@createEmptyProject');
Route::post('delImageP','ProjectMasterController@delImageP');
Route::post('delImageB','ProjectMasterController@delImageB');






// /Society Master
Route::get('society-master','SocietyMasterController@index');
Route::post('add-society-master','SocietyMasterController@add_society_master')->name('add-society-master');
Route::get('append_society_hierarchy_form','SocietyMasterController@append_society_hierarchy_form');
Route::get('append_config_sample','SocietyMasterController@append_config_sample');
Route::post('update-society-master','SocietyMasterController@update_society_master');
Route::post('getDataSociety','SocietyMasterController@getDataSociety');
Route::post('updateSocietyFormRecords','SocietyMasterController@updateSocietyFormRecords');
Route::post('deleteSocietyFormRecords','SocietyMasterController@deleteSocietyFormRecords');
Route::post('updateAmenity','SocietyMasterController@updateAmenity');

Route::get('society-list','SocietyMasterController@society_list');
Route::get('search-society-List','SocietyMasterController@search_society_list');
Route::post('getSublocationId','SocietyMasterController@getSublocationId');
Route::post('createEmptySociety','SocietyMasterController@createEmptySociety');

Route::post('delImageS','SocietyMasterController@delImageS');
Route::post('delImageConst','SocietyMasterController@delImageConst');
Route::post('delImageRS','SocietyMasterController@delImageRS');

Route::post('updateUnitAmenity','SocietyMasterController@updateUnitAmenity');





// Wing Master
Route::get('wing-master','WingMasterController@index');
Route::get('add-wing-details','WingMasterController@add_wing_details');
Route::post('add-wing-master','WingMasterController@add_wing_master')->name('add-wing-master');
Route::post('add_unit_info','WingMasterController@add_unit_info');
Route::get('add_unit_master_data','WingMasterController@add_unit_master_data');
Route::post('update-wing-master','WingMasterController@update_wing_master');
Route::post('removeWing','WingMasterController@removeWing');
Route::post('replicaWing','WingMasterController@replicaWing');

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

app/View/Components/FooterLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class FooterLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.footer');
    }
}

app/View/Components/HeaderLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class HeaderLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        $headerName = "BUYER INPUT FORM";
        return view('layouts.header',['headerName'=>$headerName]);
    }
}

app/View/Components/SidebarLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;
use App\Traits\DatabaseTrait;
use App\Http\Controllers\AccessGroupHelper;

class SidebarLayout extends Component
{
    use DatabaseTrait;

    // public $access_check_buyer;
    // public $access_check_tenant;
    // public $access_check_property_consultant;
    // public $access_check_building_master;
    // public $access_check_users;
    // public $access_check_roles;
    
    // public function __construct($access_check_buyer,$access_check_tenant,$access_check_property_consultant,$access_check_building_master,$access_check_users,$access_check_roles)
    // {       
    //     $this->access_check_buyer = $access_check_buyer;
    //     $this->access_check_tenant = $access_check_tenant;
    //     $this->access_check_property_consultant = $access_check_property_consultant;
    //     $this->access_check_building_master = $access_check_building_master;
    //     $this->access_check_users = $access_check_users;
    //     $this->access_check_roles = $access_check_roles;
    // }

    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        $data['role'] = $this->getRole();
        $data['roles'] = $this->adminRoles();

        $page_action = 's_view';
        $action_status = 1;
        $condition_name_buyer = 'buyer';
        $condition_name_tenant = 'tenant';
        $condition_name_property_consultant = 'property_consultant';
        $condition_name_building_master = 'building_master';
        $condition_name_users = 'users';
        $condition_name_roles = 'roles';
        $access_check_buyer = AccessGroupHelper::globalAccessGroupVar($condition_name_buyer,$page_action,$action_status);
        $access_check_tenant = AccessGroupHelper::globalAccessGroupVar($condition_name_tenant,$page_action,$action_status);
        $access_check_property_consultant = AccessGroupHelper::globalAccessGroupVar($condition_name_property_consultant,$page_action,$action_status);
        $access_check_building_master = AccessGroupHelper::globalAccessGroupVar($condition_name_building_master,$page_action,$action_status);
        $access_check_users = AccessGroupHelper::globalAccessGroupVar($condition_name_users,$page_action,$action_status);
        $access_check_roles = AccessGroupHelper::globalAccessGroupVar($condition_name_roles,$page_action,$action_status);

        $data['access_check_buyer'] = $access_check_buyer;
        $data['access_check_tenant'] = $access_check_tenant;
        $data['access_check_property_consultant'] = $access_check_property_consultant;
        $data['access_check_building_master'] = $access_check_building_master;
        $data['access_check_users'] = $access_check_users;
        $data['access_check_roles'] = $access_check_roles;

        return view('layouts.sidebar',$data);
    }
}

resources/views/dashboard.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Dashboard') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 bg-white border-b border-gray-200">
                    You're logged in!
                </div>
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/dashboard1.blade.php
<!-- Header Layout start -->
<x-header-layout></x-header-layout>
<!-- Header Layout end -->
      <!-- BEGIN: SideNav-->

      @php
      $check_s_view_buyer = 0;
      $check_s_view_tenant = 0;
      $check_s_view_property_consultant = 0;
      $check_s_view_building_master = 0;
      $check_s_view_users = 0;
      $check_s_view_roles = 0;
      @endphp

      @if(isset($access_check_buyer) && !empty($access_check_buyer))
         @foreach($access_check_buyer as $acbvalue)
            @php
            $check_s_view_buyer = $acbvalue->s_view;
            @endphp
         @endforeach
      @endif

      @if(isset($access_check_tenant) && !empty($access_check_tenant))
         @foreach($access_check_tenant as $actvalue)
            @php
            $check_s_view_tenant = $actvalue->s_view;
            @endphp
         @endforeach
      @endif

      @if(isset($access_check_property_consultant) && !empty($access_check_property_consultant))
         @foreach($access_check_property_consultant as $acpcvalue)
            @php
            $check_s_view_property_consultant = $acpcvalue->s_view;
            @endphp
         @endforeach
      @endif

      @if(isset($access_check_building_master) && !empty($access_check_building_master))
         @foreach($access_check_building_master as $acbmvalue)
            @php
            $check_s_view_building_master = $acbmvalue->s_view;
            @endphp
         @endforeach
      @endif

      @if(isset($access_check_users) && !empty($access_check_users))
         @foreach($access_check_users as $acuvalue)
            @php
            $check_s_view_users = $acuvalue->s_view;
            @endphp
         @endforeach
      @endif

      @if(isset($access_check_roles) && !empty($access_check_roles))
         @foreach($access_check_roles as $acrvalue)
            @php
            $check_s_view_roles = $acrvalue->s_view;
            @endphp
         @endforeach
      @endif

    @if($check_s_view_buyer==1 || $check_s_view_tenant==1 || $check_s_view_property_consultant==1 || 
      $check_s_view_building_master==1 || $check_s_view_users==1 || $check_s_view_roles==1 )
      
        <x-sidebar-layout></x-sidebar-layout>
    @endif

      <!-- END: SideNav-->
      <meta name="csrf-token" content="{{ csrf_token() }}">
      
      <link rel="stylesheet" type="text/css" href="{{ asset('app-assets/vendors/data-tables/css/jquery.dataTables.min.css')}}">
    
      <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/fixedcolumns/4.1.0/css/fixedColumns.dataTables.min.css">

<style>
  select
{
    display: block !important;
}

</style>

      <!-- BEGIN: Page Main class="main-full"-->



      <div id="main" class="main-full" style="min-height: auto">
  
        <div class="row" style="padding: 20px 0;">

            <div class="col l12 s12">
                <h1 style="text-align: center;">Welcome to Dashboard</h1>
            </div>
        </div>
      </div>

<!-- Footer layout start -->
<x-footer-layout></x-footer-layout>
<!-- Footer layout End -->
    

 <!-- END: Footer-->
    <!-- BEGIN VENDOR JS-->
    <!-- <script src="app-assets/js/vendors.min.js"></script> -->
    <!-- BEGIN VENDOR JS-->
    <!-- BEGIN PAGE VENDOR JS-->
    <script src="{{ asset('app-assets/vendors/data-tables/js/jquery.dataTables.min.js')}}"></script>
 
    <!-- BEGIN PAGE LEVEL JS-->
    <script src="{{ asset('app-assets/js/scripts/data-tables.js')}}"></script>
    <script type="text/javascript" src="https://cdn.datatables.net/fixedcolumns/4.1.0/js/dataTables.fixedColumns.min.js"></script>
    <!-- END PAGE LEVEL JS-->

resources/views/lead_details3.blade.php
<!-- Header Layout start -->
<x-header-layout></x-header-layout>
<!-- Header Layout end -->
      <!-- BEGIN: SideNav-->
      <x-sidebar-layout></x-sidebar-layout>
      <!-- END: SideNav-->
      <meta name="csrf-token" content="{{ csrf_token() }}">
      
      <link rel="stylesheet" type="text/css" href="{{ asset('app-assets/vendors/data-tables/css/jquery.dataTables.min.css')}}">
      <!-- <link rel="stylesheet" type="text/css" href="app-assets/vendors/data-tables/extensions/responsive/css/responsive.dataTables.min.css"> -->
      <!-- <link rel="stylesheet" type="text/css" href="app-assets/vendors/data-tables/css/select.dataTables.min.css"> -->
  
      <!-- <script src="app-assets/js/scripts/data-tables.js"></script> -->
      <!-- <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/fixedcolumns/3.2.0/css/fixedColumns.dataTables.min.css"> -->
      <!-- END PAGE LEVEL JS-->






      <style>


div.dataTables_wrapper {
    width: 100% !important;
    margin: 0 auto;
}
select {
    display: initial !important; ;
}

/*::-webkit-scrollbar {
  display: none;
}*/
input:focus::placeholder {
  color: transparent;
}

.select2-container--default .select2-selection--multiple:before {
    content: ' ';
    display: block;
    position: absolute;
    border-color: #888 transparent transparent transparent;
    border-style: solid;
    border-width: 5px 4px 0 4px;
    height: 0;
    right: 6px;
    margin-left: -4px;
    margin-top: -2px;top: 50%;
    width: 0;cursor: pointer
}

.select2-container--open .select2-selection--multiple:before {
    content: ' ';
    display: block;
    position: absolute;
    border-color: transparent transparent #888 transparent;
    border-width: 0 4px 5px 4px;
    height: 0;
    right: 6px;
    margin-left: -4px;
    margin-top: -2px;top: 50%;
    width: 0;cursor: pointer
}

.dataTables_filter input {
    border: 1px solid #aaa;
    border-radius: 3px;
    padding: 0px !important;
}
 


.dataTables_scrollBody{
    height: auto !important;
}


</style>
<style>
        #loader {
            border: 12px solid #f3f3f3;
            border-radius: 50%;
            border-top: 12px solid #444444;
            width: 70px;
            height: 70px;
            animation: spin 1s linear infinite;
        }
          
        @keyframes spin {
            100% {
                transform: rotate(360deg);
            }
        }
          
        .center {
            position: absolute;
            top: 0;
            bottom: 0;
            left: 0;
            right: 0;
            margin: auto;
        }
    </style>

<script src="{{ asset('app-assets/js/custom/buyer.js') }}"></script>
      <!-- BEGIN: Page Main class="main-full"-->
  
      <div id="main" class="main-full" style="min-height: auto">
         <div class="row">
         <div id="loader" class="center"></div>
         <input type="hidden" value="@if(isset($buyerId) && !empty($buyerId)) {{$buyerId['buyer_tenant_id']}} @endif" id="buyer_tenant_id">
         <input type="hidden"  id="customer_id" value="@if(isset($getCustomerData) && !empty($getCustomerData)) {{$getCustomerData[0]->id}} @endif">
           
               <x-leadinfor1-layout :buyerId="$buyerId"  :getBuyerData="$getBuyerData" :getCustomerData="$getCustomerData" :getLeadSourceData="$getLeadSourceData"></x-leadinfor1-layout>
                <x-requirementr1-layout :getBuyerData="$getBuyerData" :getSpecificChoiceData="$getSpecificChoiceData"></x-requirementr1-layout>
                <x-requirementr2-layout :getBuyerData="$getBuyerData" :getPropertySeenData="$getPropertySeenData"  :getCustomerData="$getCustomerData" :getSpecificChoiceData="$getSpecificChoiceData"></x-requirementr2-layout>
                <x-requirementr3-layout :getBuyerData="$getBuyerData" :getSpecificChoiceData="$getSpecificChoiceData"></x-requirementr3-layout>
                
                <x-requirementr5-layout ></x-requirementr5-layout>
            <hr>                   
            <x-requirementr6-layout :getBuyerData="$getBuyerData" :getmemberData="$getmemberData" :getChallengesData="$getChallengesData"></x-requirementr6-layout>
            

            <!-- <a href="#" onClick="saveBuyer()">Save</a> -->
            <x-all_modals-layout></x-all_modals-layout>
            <x-all_modals-layout></x-all_modals-layout>
             <hr>

             <div class="row">
                 <div class="input-field col l3 m4 s12" id="InputsWrapper2">

                    <div class="row" >
                        <div class="input-field col l2 m2 s6 display_search">
                        <div class="preloader-wrapper small active" id="loader5" style="display:none">
                            <div class="spinner-layer spinner-green-only">
                            <div class="circle-clipper left">
                                <div class="circle"></div>
                            </div><div class="gap-patch">
                                <div class="circle"></div>
                            </div><div class="circle-clipper right">
                                <div class="circle"></div>
                            </div>
                            </div>
                        </div>
                        </div>
                    </div>

                    <div class="row" id="submitMain">
                        <div class="col l4 m4">
                            <a href="javascript:void(0)" onClick="saveBuyer()" class=" save_challeges_solution btn-small  waves-effect waves-light green darken-1 " id="save_challeges_solution">Save</a>
                        </div>
                        
                    </div>
                </div> 
             </div>
             <!-- Code by avinash -->
 </div>
            
  
 
                  <!-- START RIGHT SIDEBAR NAV -->
               </div>
               <div class="content-overlay"></div>
            </div>
         </div>
      </div>
      <!-- END: Page Main-->
      <!-- </div>
        </div> -->
        <script>
        document.onreadystatechange = function() {
            if (document.readyState !== "complete") {
                document.querySelector(
                  "body").style.visibility = "hidden";
                document.querySelector(
                  "#loader").style.visibility = "visible";
            } else {
                document.querySelector(
                  "#loader").style.display = "none";
                document.querySelector(
                  "body").style.visibility = "visible";
            }
        };
    </script>

        

<!-- Footer layout start -->
<x-footer-layout></x-footer-layout>
<!-- Footer layout End -->
    

 <!-- END: Footer-->
    <!-- BEGIN VENDOR JS-->
    <!-- <script src="app-assets/js/vendors.min.js"></script> -->
    <!-- BEGIN VENDOR JS-->
    <!-- BEGIN PAGE VENDOR JS-->
    <script src="{{ asset('app-assets/vendors/data-tables/js/jquery.dataTables.min.js')}}"></script>
    <!-- <script src="app-assets/vendors/data-tables/extensions/responsive/js/dataTables.responsive.min.js"></script> -->
    <!-- <script src="app-assets/vendors/data-tables/js/dataTables.select.min.js"></script> -->
    <!-- END PAGE VENDOR JS-->
    <!-- BEGIN THEME  JS-->
    <!-- <script src="app-assets/js/plugins.js"></script> -->
    <!-- <script src="app-assets/js/search.js"></script> -->
    <!-- <script src="app-assets/js/custom/custom-script.js"></script> -->
    <!-- END THEME  JS-->
    <!-- BEGIN PAGE LEVEL JS-->
    <script src="{{ asset('app-assets/js/scripts/data-tables.js')}}"></script>
    <!-- END PAGE LEVEL JS-->

resources/views/new_user.blade.php
<!-- Header Layout start -->
<x-header-layout></x-header-layout>
<!-- Header Layout end -->
      <!-- BEGIN: SideNav-->
      <x-sidebar-layout></x-sidebar-layout>
      <!-- END: SideNav-->
      <style>
            ::-webkit-scrollbar {
            display: none;
            }
            input:focus::placeholder {
            color: transparent;
            }

            /* .select2-container--default .select2-selection--multiple:before {
                content: ' ';
                display: block;
                position: absolute;
                border-color: #888 transparent transparent transparent;
                border-style: solid;
                border-width: 5px 4px 0 4px;
                height: 0;
                right: 6px;
                margin-left: -4px;
                margin-top: -2px;top: 50%;
                width: 0;cursor: pointer
            }

            .select2-container--open .select2-selection--multiple:before {
                content: ' ';
                display: block;
                position: absolute;
                border-color: transparent transparent #888 transparent;
                border-width: 0 4px 5px 4px;
                height: 0;
                right: 6px;
                margin-left: -4px;
                margin-top: -2px;top: 50%;
                width: 0;cursor: pointer
            } */

      </style>
      

     
     <div id="main" class="main-full" >
        
           
           
            
        <div class="container" style="font-weight: 600;text-align: center;margin-top: 5px;"> <span class="userselect">ADD NEW USER</span><hr> 
        <x-leadinfor1-layout></x-leadinfor1-layout>
        </div>

    </div>
         
      <!-- END: Page Main-->
      <!-- </div>
        </div> -->


        

<!-- Footer layout start -->
<x-footer-layout></x-footer-layout>
<!-- Footer layout End -->
     

resources/views/owner.blade.php
<!-- Header Layout start -->
<x-header-layout></x-header-layout>
<!-- Header Layout end -->
      <!-- BEGIN: SideNav-->
      <x-sidebar-layout></x-sidebar-layout>
      <!-- END: SideNav-->
      <style>
::-webkit-scrollbar {
  display: none;
}
input:focus::placeholder {
  color: transparent;
}

.select2-container--default .select2-selection--multiple:before {
    content: ' ';
    display: block;
    position: absolute;
    border-color: #888 transparent transparent transparent;
    border-style: solid;
    border-width: 5px 4px 0 4px;
    height: 0;
    right: 6px;
    margin-left: -4px;
    margin-top: -2px;top: 50%;
    width: 0;cursor: pointer
}

.select2-container--open .select2-selection--multiple:before {
    content: ' ';
    display: block;
    position: absolute;
    border-color: transparent transparent #888 transparent;
    border-width: 0 4px 5px 4px;
    height: 0;
    right: 6px;
    margin-left: -4px;
    margin-top: -2px;top: 50%;
    width: 0;cursor: pointer
}

      </style>
      

      <!-- BEGIN: Page Main class="main-full"-->
      <!-- <div id="container1"><div id="container2"> -->
      <div id="main" class="main-full" style="min-height: auto">
         <div class="row">
           
           
            <!-- <div class="col s12"> -->
               <!-- <div class="container" style="font-weight: 600;text-align: center;margin-top: 5px;"> <span class="userselect">BUYER INPUT FORM</span><hr>  </div> -->
                 <x-ownerrow1-layout></x-ownerrow1-layout>
                 <x-ownerrow2-layout></x-ownerrow2-layout>
                 <x-ownerrow3-layout></x-ownerrow3-layout>
                 <x-ownerrow4-layout></x-ownerrow4-layout>
                 <hr>
                 <x-ownerrow5-layout></x-ownerrow5-layout>              
      

                 <x-all_modals-layout></x-all_modals-layout>               
            <!-- </div>                                      -->
            

                
                  <!-- START RIGHT SIDEBAR NAV -->
               </div>
               <div class="content-overlay"></div>
            </div>
         </div>
      </div>
      <!-- END: Page Main-->
      <!-- </div>
        </div> -->


        

<!-- Footer layout start -->
<x-footer-layout></x-footer-layout>
<!-- Footer layout End -->
     